### ISSUE TITLE
 interaction.member.roles.add is not a function

### ISSUE THREAD

**Issue by jatindhawan** [dylan-p-wong/stripe-discord-renewal#17]
TypeError: interaction.member.roles.add is not a function
    at run (/Users/jatindhawan/code/stripe-discord-bot/dist/slash-commands/email.js:61:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: interaction.member.roles.add is not a function
    at run (/Users/jatindhawan/code/stripe-discord-bot/dist/slash-commands/email.js:61:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dylan-p-wong** [comment]
This project is very old. I do not have enough time at the moment to work on this but if there is significant interest I may do a rewrite in the future.
